[tool.poetry]
name = "octopus"
version = "0.1.0"
description = ""
authors = ["Jean-Baptiste Doderlein <jean-baptiste.doderlein@ens-rennes.fr>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
